
CREATE TABLE EventPlanLine(
PlanNo VARCHAR2(8) CONSTRAINT PlanNoEPLFKNOTNULL NOT NULL,
LineNo INTEGER CONSTRAINT LineNoNotNull NOT NULL,
TimeStart DATE CONSTRAINT TimeStartNotNull NOT NULL,
TimeEnd DATE CONSTRAINT TimeEndNotNull NOT NULL,
NumberFld INTEGER CONSTRAINT NumberFldNotNull NOT NULL,
LocNo VARCHAR2(8) CONSTRAINT LocNoEPLFKNotNull NOT NULL,
ResNo VARCHAR2(8) CONSTRAINT ResNoEPLFKNotNull NOT NULL,
CONSTRAINT PK_EVENTPLANLINE PRIMARY KEY (PlanNo,LineNo),
CONSTRAINT FK_EPLPLANNO FOREIGN KEY (PlanNo) REFERENCES EventPlan (PlanNo),
CONSTRAINT FK_EPLLOCNO FOREIGN KEY (LocNo) REFERENCES Location (LocNo),
CONSTRAINT FK_EPLRESNO FOREIGN KEY (ResNo) REFERENCES ResourceTbl (ResNo),
CONSTRAINT CHECK_VALIDDURATION CHECK(TimeStart<TimeEnd)
);

