

CREATE TABLE EventPlan(
PlanNo VARCHAR2(8) CONSTRAINT PlanNoNotNull NOT NULL,
EventNo VARCHAR2(8) CONSTRAINT EventNoEPFKNotNull NOT NULL,
WorkDate DATE CONSTRAINT WorkDateNotNull NOT NULL,
Notes VARCHAR2(50),
Activity VARCHAR2(30) CONSTRAINT ActivityNotNull NOT NULL,
EmpNo VARCHAR2(8),
CONSTRAINT PK_EVENTPLAN PRIMARY KEY (PlanNo),
CONSTRAINT FK_EPEVENTNO FOREIGN KEY (EventNo) REFERENCES EventRequest(EventNo),
CONSTRAINT FK_EPEMPNO FOREIGN KEY (EmpNo) REFERENCES Employee(EmpNo),
CONSTRAINT CHECK_ACTIVITY CHECK (Activity IN ('Operation','Cleanup','Setup'))
);
