CREATE TABLE Employee(
EmpNo VARCHAR2(8) CONSTRAINT EmpNoNotNull NOT NULL,
EmpName VARCHAR2(30) CONSTRAINT EmpNameNotNull NOT NULL,
Department VARCHAR2(30) CONSTRAINT DepartmentNotNull NOT NULL,
Email VARCHAR2(50) CONSTRAINT EmailNotNull NOT NULL,
Phone VARCHAR2(20) CONSTRAINT PhoneNotNull NOT NULL,
CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EmpNo),
CONSTRAINT UNIQUE_EMAIL UNIQUE (Email)
);
