
CREATE TABLE EventRequest(
EventNo VARCHAR2(8) CONSTRAINT EventNoNotNull NOT NULL,
DateHeld DATE CONSTRAINT DateHeldNotNull NOT NULL,
DateReq DATE CONSTRAINT DateReqNotNull NOT NULL,
CustNo VARCHAR2(8) CONSTRAINT CustNoERFKNotNull NOT NULL,
FacNo VARCHAR2(8) CONSTRAINT FacNoERFKNotNull NOT NULL,
DateAuth DATE,
Status VARCHAR2(20) CONSTRAINT StatusNotNull NOT NULL,
EstCost INTEGER CONSTRAINT EstCostNotNull NOT NULL,
EstAudience INTEGER CONSTRAINT EstAudienceNotNull NOT NULL,
BudNo VARCHAR2(10),
CONSTRAINT PK_EVENTREQUEST PRIMARY KEY (EventNo),
CONSTRAINT FK_ERFACNO FOREIGN KEY (FacNo) REFERENCES FACILITY(FacNo),
CONSTRAINT FK_ERCUSTNO FOREIGN KEY (CustNo) REFERENCES CUSTOMER(CustNo),
CONSTRAINT CHECK_ESTAUDIENCE CHECK (EstAudience>0),
CONSTRAINT CHECK_STATUS CHECK (Status IN ('Approved','Denied','Pending'))
);