SELECT EVENTREQUEST.EVENTNO, DATEHELD, COUNT(*) 
FROM EVENTREQUEST 
INNER JOIN EVENTPLAN 
ON EVENTREQUEST.EVENTNO = EVENTPLAN.EVENTNO 
WHERE WORKDATE BETWEEN '01-DEC-13' AND '31-DEC-13'
GROUP BY EVENTREQUEST.EVENTNO, DATEHELD 
HAVING COUNT(*)>1;

SELECT PLANNO, EVENTPLAN.EVENTNO, WORKDATE,ACTIVITY 
FROM EVENTPLAN INNER JOIN EVENTREQUEST 
ON EVENTPLAN.EVENTNO=EVENTREQUEST.EVENTNO
INNER JOIN FACILITY 
ON EVENTREQUEST.FACNO=FACILITY.FACNO
WHERE (WORKDATE BETWEEN '01-DEC-13' AND '31-DEC-13' )
AND FACNAME='Basketball arena';

SELECT EVENTREQUEST.EVENTNO, DATEHELD, STATUS, ESTCOST 
FROM FACILITY INNER JOIN EVENTREQUEST
ON FACILITY.FACNO=EVENTREQUEST.FACNO
INNER JOIN EVENTPLAN
ON EVENTREQUEST.EVENTNO=EVENTPLAN.EVENTNO
INNER JOIN EMPLOYEE 
ON EMPLOYEE.EMPNO=EVENTPLAN.EMPNO
WHERE EMPNAME='Mary Manager' 
AND FACNAME='Basketball arena'
AND (DATEHELD BETWEEN '01-OCT-13' AND '31-DEC-13');

SELECT EVENTPLANLINE.PLANNO, LINENO, RESNAME, NUMBERFLD, LOCNAME, TIMESTART, TIMEEND 
FROM EVENTPLANLINE 
INNER JOIN RESOURCETBL
ON RESOURCETBL.RESNO=EVENTPLANLINE.RESNO
INNER JOIN LOCATION
ON LOCATION.LOCNO=EVENTPLANLINE.LOCNO
INNER JOIN FACILITY
ON FACILITY.FACNO=LOCATION.FACNO
INNER JOIN EVENTPLAN
ON EVENTPLAN.PLANNO=EVENTPLANLINE.PLANNO
WHERE ACTIVITY='Operation' 
AND FACNAME='Basketball arena'
AND (WORKDATE BETWEEN '01-OCT-13' AND '31-DEC-13');
 
INSERT INTO FACILITY (FACNO,FACNAME) VALUES ('F104','Swimming Pool');

INSERT INTO LOCATION (LOCNO, FACNO, LOCNAME) VALUES ('L107','F104','Door');

INSERT INTO LOCATION (LOCNO, FACNO, LOCNAME) VALUES ('L108','F104','Locker room');

UPDATE LOCATION SET LOCNAME='Gate' WHERE LOCNO='L107';

DELETE FROM LOCATION WHERE LOCNO='L108';

