
SELECT EVENTPLANLINE.PLANNO, LINENO, RESNAME, NUMBERFLD, LOCNAME, TIMESTART, TIMEEND 
FROM EVENTPLANLINE 
INNER JOIN RESOURCETBL
ON RESOURCETBL.RESNO=EVENTPLANLINE.RESNO
INNER JOIN LOCATION
ON LOCATION.LOCNO=EVENTPLANLINE.LOCNO
INNER JOIN FACILITY
ON FACILITY.FACNO=LOCATION.FACNO
INNER JOIN EVENTPLAN
ON EVENTPLAN.PLANNO=EVENTPLANLINE.PLANNO
WHERE ACTIVITY='Operation' 
AND FACNAME='Basketball arena'
AND (WORKDATE BETWEEN '01-OCT-13' AND '31-DEC-13');
